name: Selenium Tests

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Run Selenium Tests
        run: mvn test -Psmoke -Dbrowser=chromeheadless

      - name: Upload Extent Report
        if: always()
        uses: actions/upload-artifact@v6
        with:
          name: extent-report
          path: reports/